Bmerketo/Controllers/Management/ColorController.cs
using Bmerketo.Contexts;
using Bmerketo.Models.Entities;
using Bmerketo.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace Bmerketo.Controllers.Management
{
    public class ColorController : Controller
    {
        private readonly IColorInterface _colorService;

        public ColorController(IColorInterface Service)
        {
            _colorService = Service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _colorService.GetAllAsync();
            return View(data);
        }
        //Get
        public IActionResult Create()
        {
            return View();
        }
        //Set
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ColorName")] ColorEntity color)
        {
            if (!ModelState.IsValid)
            {
                return View(color);
            }
            await _colorService.AddAsync(color);
            return RedirectToAction(nameof(Index));
        }

        //------------------------

        //Get
        public async Task<IActionResult> Edit(int id)
        {
            var colorName = await _colorService.GetByIdAsync(id);
            if (colorName == null) { return View("NotFound"); }


            return View(colorName);
        }
        //Set
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ColorName")] ColorEntity color)
        {
            if (!ModelState.IsValid)
            {
                return View(color);
            }
            await _colorService.UpdateAsync(id, color);
            return RedirectToAction(nameof(Index));
        }


        //-------------------------
        public async Task<IActionResult> Detials(int id)
        {
            var colorDetails = _colorService.GetByIdAsync(id);
            if (colorDetails == null)
                return View("Empty");
            return View(colorDetails);
        }

        //------------***********-------------
        //Get
        public async Task<IActionResult> Delete(int id)
        {
            var colorName = await _colorService.GetByIdAsync(id);
            if (colorName == null) { return View("NotFound"); }


            return View(colorName);
        }
        //Set
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            var colorName = await _colorService.GetByIdAsync(id);
            if (colorName == null) { return View("NotFound"); }
            await _colorService.DeleteAsync(id);


            return RedirectToAction(nameof(Index));
        }
    }

}

Bmerketo/Views/Color/Create.cshtml
@model Bmerketo.Models.Entities.ColorEntity

@{
    ViewData["Title"] = "Crad ";
    Layout = "~/Views/Shared/_LayoutCenterScreen.cshtml";
}
<div class="Row text">
    <div class="col-md-8" offset-2>
        <p> <h1>Add a new Color</h1></p>
        <div class="Row">
            <div class="col-md-8" offset-2>
                <form asp-action="Create">
                    <div asp.asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group">
                        <label asp-for="ColorName"></label>
                        <input asp-for="ColorName" class="form-control" />
                        <span asp-validation-for="ColorName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

Bmerketo/Views/Color/Delete.cshtml
@model Bmerketo.Models.Entities.ColorEntity

@{
    ViewData["Title"] = "Delete ";
    Layout = "~/Views/Shared/_LayoutCenterScreen.cshtml";
}
<div class="Row text">
    <div class="col-md-8" offset-2>
        <p> <h1>Delete</h1></p>
        <div class="Row">
            <div class="col-md-8" offset-2>

                <div asp.asp-validation-summary="ModelOnly" class="text-danger">
                </div>
                <div class="form-group">
                    <label asp-for="ColorName"></label>
                    <input asp-for="ColorName" class="form-control" readonly />

                </div>
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id"/>
                        <button type="submit" value="Confirm" class="btn btn-danger float-right">Delete</button>
                    </form>
                    <a class="btn btn-outline-secondary float-laft" asp-action="Index">Show All</a>
                    
                </div>


            </div>
        </div>
    </div>
</div>

Bmerketo/Views/Color/Detials.cshtml
@model Bmerketo.Models.Entities.ColorEntity

@{
    ViewData["Title"] = "Detials ";
    Layout = "~/Views/Shared/_LayoutCenterScreen.cshtml";
}
<div class="Row text">
    <div class="col-md-8" offset-2>
        <p> <h1>Detials</h1></p>
        <div class="Row">
            <div class="col-md-8" offset-2>
              
                    <div asp.asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group">
                        <label asp-for="ColorName"></label>
                        <input asp-for="ColorName" class="form-control" readonly />
                       
                    </div>
                    <div class="form-group">                        
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
              

            </div>
        </div>
    </div>
</div>

Bmerketo/Views/Color/Edit.cshtml
@model Bmerketo.Models.Entities.ColorEntity

@{
    ViewData["Title"] = "Update ";
    Layout = "~/Views/Shared/_LayoutCenterScreen.cshtml";
}
<div class="Row text">
    <div class="col-md-8" offset-2>
        <p> <h1>Update Color</h1></p>
        <div class="Row">
            <div class="col-md-8" offset-2>
                <form asp-action="Edit">
                    <div asp.asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    <div class="form-group">
                        <label asp-for="ColorName"></label>
                        <input asp-for="ColorName" class="form-control" />
                        <span asp-validation-for="ColorName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>


      

Bmerketo/Views/Color/Index.cshtml
@model IEnumerable<Bmerketo.Models.Entities.ColorEntity>


@{
    ViewData["Title"] = "Brand";
}

<div class="row">


    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>@Html.DisplayNameFor(model => model.ColorName)</th>

                    <th>Actions</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.ColorName)
                        </td>

                        @* @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {*@
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-file-pen"></i> Edit </a> 
                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-id="@item.Id"><i class="fa-solid fa-trash"></i> Delete </a>
                        </td>
                        @* }*@

                    </tr>
                }
            </tbody>

        </table>



    </div>
</div>
<div class="text-white" style="position:  fixed; right:25px; bottom: 25px;">
    <a class="btn btn-success text-white" asp-controller="Color" asp-action="Create"><i class="fa-regular fa-plus"></i> New </a>
</div>
@*@await Html.PartialAsync("_CreateItem", "BrandEntity") *@